name: check

on:
  push:
    branches:
      - main

  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup dependencies
        run: npm install

      - name: check lint
        run: npm run lint
        
      - name: Check typescript
        run: npm run ts-check

      - name: check unit test
        run: npm run test
